In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
import string

punctuations = list(string.punctuation) # Get all punctuation : !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [ ]:
import kagglehub
import pandas as pd
import os


path = kagglehub.dataset_download("emineyetm/fake-news-detection-datasets")


data_path = os.path.join(path, "News _dataset")

print("Files:", os.listdir(data_path))


fake_df = pd.read_csv(os.path.join(data_path, "Fake.csv"))
true_df = pd.read_csv(os.path.join(data_path, "True.csv"))

print(fake_df.head())
print(true_df.head())

Using Colab cache for faster access to the 'fake-news-detection-datasets' dataset.
Files: ['True.csv', 'Fake.csv']
                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date
0  December 31, 2017
1  December 31, 2017
2  December 30, 2017
3  December 29, 2017
4  December 25, 2017
                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date
0  December 31, 2017
1  December 29, 2017
2  December 31, 2017
3  December 30, 2017
4  December 29, 2017

In [ ]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
fake_df['label'] = 0
true_df['label'] = 1

In [ ]:
true_df_cols = true_df.columns
fake_df_cols = fake_df.columns

print (true_df_cols)
print (fake_df_cols)

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')
Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [ ]:
data = pd.concat([fake_df, true_df], ignore_index=True)
data = data.sample(frac=1, random_state=42).reset_index(drop=True) #shuffle the dataset

data.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [ ]:
X = data['text'].tolist()[:500]
y = data['label'].tolist()[:500]
print(X)

['21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: 21st Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV', 'WASHINGTON (Reuters) - U.S. President Donald Trump removed his chief strategist Steve Bannon from the National Security Council on Wednesday, reversing his controversial decision early this year to give a political adviser an unprecedented role in security discussions. Trump’s overhaul of the NSC, confirmed by a White House official, also elevated General Joseph Dunford, chairman of the Joint Chiefs of Staff and Dan Coats, the director of National Intelligence who heads all 17 U.S. intelligence agencies. The official said the change moves the NSC “back to its core function of what it’s supposed to do.” It also appears to mark a victory for national security adviser H.R. McMaster, who had told some national security experts he felt he was in a “battle to the death” with Bannon and others on the White House staff. Vice President Mike Pence said Bannon would continue to play an important role in policy and played down the shake-up as routine. “This is just a natural evolution to ensure the National Security Council is organized in a way that best serves the president in resolving and making those difficult decisions,” Pence said on Fox News.  Bannon said in a statement he had succeeded in returning the NSC back to its traditional role of coordinating foreign policy rather than running it. He cited President Barack Obama’s national security adviser, Susan Rice, for why he advocated a change. “Susan Rice operationalized the NSC during the last administration so I was put on NSC to ensure it was ‘de-operationalized.’ General McMaster has NSC back to its proper function,” he said. Trump’s White House team has grappled with infighting and intrigue that has hobbled his young presidency. In recent days, several other senior U.S. foreign policy and national security officials have said the mechanisms for shaping the Trump administration’s response to pressing challenges such as Syria, North Korea and Iran still were not in place.  Critics of Bannon’s role on the NSC said it gave too much weight in decision-making to someone who lacked foreign policy expertise. Bannon, who was chief executive of Trump’s presidential campaign in the months leading to his election in November, in some respects represents Trump’s “America First” nationalistic voice, helping fuel his anti-Washington fervor and pushing for the president to part ways at times with mainstream Republicans. Before joining the Trump administration, Bannon headed Breitbart News, a right-wing website. U.S. Representative Adam Schiff, ranking Democrat on the House of Representatives Intelligence Committee, called the shift in the NSC a positive step that will help McMaster “gain control over a body that was being politicized by Bannon’s involvement.” “As the administration’s policy over North Korea, China, Russia and Syria continues to drift, we can only hope this shake-up brings some level of strategic vision to the body,” he said. Bannon’s removal from the NSC was a potential setback for his sphere of influence in the Trump White House, where he has a voice in most major decisions. But a Trump confidant said Bannon remained as influential as ever. “He is still involved in everything and still has the full confidence of the president but to be fair he can only do so much stuff,” the confidant said, speaking on condition of anonymity. The White House official said Bannon was no longer needed on the NSC after the departure of Trump’s first national security adviser, Michael Flynn. Flynn was forced to resign on Feb. 13 over his contacts with Russia’s ambassador to the United States, Sergei Kislyak, prior to Trump taking office on Jan. 20. The official said Bannon had been placed on the NSC originally as a check on Flynn and had only attended one of the NSC’s regular meetings. The official dismissed questions about a power struggle between Bannon and McMaster, saying they shared the same world view. However, two current national security officials rejected the White House explanation, noting that two months have passed since Flynn’s departure. McMaster, they said, speaking on the condition of anonymity, also has dueled with Bannon and others over direct access to Trump; the future of deputy national security adviser K.T. McFarland, a former Fox News commentator; intelligence director Ezra Cohen-Watnick, a Flynn appointee; and other staffing decisions. Trump is preparing for his first face-to-face meeting on Thursday and Friday with Chinese President Xi Jinping with the threat of North Korea’s nuclear and missile programs a key component of their talks. Bannon’s seat on the NSC’s “principals’ committee,” a group that includes the secretaries of state, defense and other ranking aides, was taken by Rick Perry, who as energy secretary is charged with overseeing the U.S. nuclear weapons arsenal. ', '(Reuters) - Puerto Rico Governor Ricardo Rossello said on Wednesday he expected the federal government to waive the Jones Act, which would lift restrictions on ships that can provide aid to the island devastated by Hurricane Maria. He said he has been speaking with members of Congress from both parties who have supported an emergency waiver.  \xa0\xa0\xa0\xa0“We expect them to waive it,” Rossello said in an interview with CNN. He noted there was a seven-day waiver after Hurricane Irma, which was much less devastating to the island. \xa0\xa0\xa0 On Tuesday, the Trump administration said there was no need to waive shipping restrictions to help get fuel and supplies to storm-ravaged Puerto Rico, saying it would do nothing to address the island’s damaged ports, the main impediment to shipping. A waiver would allow Puerto Rico to get help not only from U.S. ships but from any ships that can bring aid. \xa0\xa0\xa0 “That is critical, particularly for fuel,” he said. “One of the considerations right now is the priority of getting fuel, diesel, gasoline, all across the island. Right now we have enough fuel. We’re limited by the transportation logistics, but at some point of course, getting fuel into the island is going to be critical so that we can have the major functions of telecoms, hospitals, water, to be running appropriately.” \xa0\xa0\xa0 The Jones Act requires that all goods shipped between U.S. ports be carried by American owned-and-operated ships. U.S. Senator John McCain asked acting Department of Homeland Security Secretary Elaine Duke on Tuesday to grant an emergency waiver of the law. He said that Puerto Rican residents would have to pay at least twice as much for food, drinking water and other supplies without the waiver. (This corrected version of the story fixes paragraph four to show the administration has not formally denied a waiver request). ', 'On Monday, Donald Trump once again embarrassed himself and his country by accidentally revealing the source of the extremely classified information he leaked to Russia earlier this month.While it was speculated that the source of the information was Israel, Trump made things crystal clear during a press conference with Prime Minister Benjamin Netanyahu. President Pussygrabber explained that he never   not once   said  Israel  during his conversation with the Russian recipients of the leaked information. Not a single time. Just so you understand I never mentioned the word or the name  Israel,  Trump said.  I never mentioned it during that conversation. They were all saying I did,  Trump said, gesturing to reporters.  So you had another story wrong. Never mentioned the word  Israel . He may not have said the word Israel,  but according to reports Israeli intelligence officials  were shouting at US counterparts  over the leaked information.Now, he accidentally-perhaps-on-purpose confirmed where it came from.Watch it happen below:President Trump says he  never mentioned the word Israel  in his Oval Office meeting with Russian officials https://t.co/84ZCW64hcE  CNN Politics (@CNNPolitics) May 22, 2017Featured image via screengrab', 'GLASGOW, Scotland (Reuters) - Most U.S. presidential candidates go abroad to sharpen their foreign policy credentials. Donald Trump arrives in Scotland on Friday to reopen a golf resort. The presumptive Republican nominee, 70, visits his family’s ancestral homeland to showcase his far-flung business empire. His mother was born on Scotland’s Isle of Lewis. With a throng of reporters watching, he will make a dramatic arrival by helicopter at his seaside Trump Turnberry resort. He has scheduled a news conference on the 9th hole at noon (7 a.m. ET/1100 GMT). His visit to Turnberry, to be followed by a stop at his resort in Aberdeen on Saturday, will allow him to comment on the outcome of Britain’s vote on Thursday on whether to remain in the European Union. “I don’t think opening a golf resort gets you many foreign policy chops,” said Saul Anuzis, former chairman of the Michigan Republican Party. “But since he’s there right in the middle of the EU vote, it may end up being a PR bonanza for him.” The risk is that the real-estate tycoon, who has yet to hold public office and rates unfavorably with 70 percent of Americans in an opinion poll, will make a foreign policy misstep at a time when Republican leaders are urging a more serious demeanor. Trump has said he would be inclined to leave the EU. He has exchanged insults with British Prime Minister David Cameron, who has called the New Yorker’s anti-immigrant policy ideas divisive and wrong. There are no plans for the two to meet. His trip has baffled Republican officials who say he should concentrate on strengthening his campaign and taking the fight to the presumptive Democratic nominee, former U.S. Secretary of State Hillary Clinton, who is 68. Trump defeated a crowded field of opponents for the Republican nomination but has faced one controversy after another, the latest over his firing of his campaign manager this week, a month before the party convention. “His campaign has got all kinds of growing pains and it doesn’t make sense that he would spend any kind of time going out of the country,” said David Yepsen, director of the Paul Simon Public Policy Institute at Southern Illinois University.  Turnberry is a storied course where the Open Championship has been staged four times. Trump invested $290 million in renovating the resort and golf course on Scotland’s West Coast 85 km (53 miles) southwest of Glasgow. He has portrayed his determination to build up courses in Turnberry and Aberdeen and overcome local opposition as an example of the type of leadership skills that Americans would get if he wins the White House on Nov. 8. “Well, Scotland has already been won – and so will the United States,” Trump wrote in a column for The Press and Journal newspaper in Aberdeen. An Aberdeen family opposed to his development there has threatened to raise a Mexican flag as a reminder of his proposal to build a wall along the U.S. southern border to keep out immigrants who enter illegally. The last Republican presidential nominee, former Massachusetts Governor Mitt Romney, in 2012 made a gaffe-filled campaign trip to London, Jerusalem and Poland. ', 'On Wednesday, Democrats took a powerful stance against the GOP s refusal to vote on gun control measures by staging a sit-in. While Republican politicians called a recess and took a lunch break, Dems stayed put on the floor and fought for the safety of America s citizens.Hours after the sit-in, House Speaker Paul Ryan weighed in on the event in an interview with CNN, and his comments were just as disappointing as they were disgusting. His response to a sit-in, which follows the deaths of almost 50 innocent Americans that lost their lives in a tragic mass shooting in Orlando a week ago, was this brutal sentence: This is nothing more than a publicity stunt. Seriously   a genuine attempt to get Congress to support gun control measures that will protect American citizens from senseless gun violence like mass shootings is considered a  publicity stunt  by a leading Republican. The Speaker of the House added that the Democrats involved in the sit-in were trying to rob Americans of their rights, insisting that we should not be focusing on gun control and that the real threat is terrorism. In saying this, Ryan has completely ignored the fact that there have been several mass shootings in the United States that have zero connection to terrorism and were caused by individuals that never should have been able to get their hands on a gun so effortlessly.To prove just how backwards Ryan s  logic  is, he accused the hard-working Democrats fighting for gun control legislation of doing the sit-in for  attention  instead of creating solutions (clearly, he forgot that his GOP colleagues were EATING LUNCH while this was happening   which definitely doesn t solve anything). When Wolf Blitzer asked Ryan if it was the NRA that was the major obstacle standing in the way of gun control legislation, Ryan said, No, the Constitution is  because Americans have a  guaranteed  Second Amendment right to firearms.You can watch Ryan s horrific comments below:The entire interview is infuriating, but truly proves that the GOP cares more about guns than Americans  right to safety.Featured image via Allison Shelley / Getty Images', 'President Trump s rally in FL on Saturday was a smashing success with about 9000 crowding into a hanger to hear him speak and another two or three times that amount congregating outside.Trump told his supporters  I want to speak to you without the filter of the fake news. The warm up act to President Trump s speech was YouTube sensations Diamond and Silk who fired up the crowd.Diamond and Silk:  Let me just say this to the media. Let me just say this. We didn t believe you in the primaries. We didn t believe you in the general election. And, read my lips, we don t believe you now! Diamond and Silk have a message for the media at @realDonaldTrump Melbourne FL rally pic.twitter.com/3b5U4UUbTO  Kristinn Taylor (@KristinnFR) February 18, 2017Me with my favorite Deplorables @DiamondandSilk! #melbourne #trumprally #trumptrain pic.twitter.com/cW2RMiIOHU  Cory Trump 2020 (@LiveLifeCorAZy) February 18, 2017(Source: Gateway Pundit)', 'He s been Europe s version of the outspoken Ted Cruz for some time now. Nigel Farage, leader of the UK Independence Party may be the most disliked member of the European Parliment. But he plows ahead, ignorning  the open sneers and insults by his fellow members of the EU Parliment.  In what must count as perhaps the worst piece of public policy seen in modern Europe for half a century. When you compound it with an already failing and flawed EU common asylum policy, by saying to the whole world,  Please come to Europe.  and we saw frankly, virtually a stampede, and we learned that 80% of those that are coming are not Syrian refugees. In fact, what you ve done is opened the door to young, male, economic migrants, many of whom I have to say behave quite in a rather an aggressive manner, quite the opposite of what you would expect to see of any refugee. And yet when that failure is met by objections from countries like Hungary, their opinions are crushed.  This isn t a Europe of peace, it s a Europe of division, it s a Europe of disharmony, it s a Europe that s a recipe for resentment. And yet, faced with all this failure, both of you said the same thing today. You said,  Europe isn t working so let s have some more Europe, more of the same failing.  Well there is I think, a bright star on the horizon. It s called the British referendum. And given that none of you want to concede Britain the ability to take back control of her own borders, a  Brexit  now, looks more likely than at any other time. We could use about 100 Nigel Farage s in our U.S. Congress .https://youtu.be/GbJp8zxduWk', 'WASHINGTON (Reuters) - The State Department said Wednesday that the United States would be open to talking to North Korea  when the time is right  but that it could not happen now because Pyongyang has shown no sign of a willingness to halt its missile and nuclear testing. Despite U.S. Secretary of State Rex Tillerson s offer on Tuesday to start talks with North Korea without pre-conditions, State Department spokeswoman Heather Nauert said there would first have to be a  period of calm  in which Pyongyang suspends  testing before any negotiations could begin. Tillerson, in a speech to a Washington think tank on Tuesday, did not explicitly establish such a freeze as a requirement that North Korea must meet ahead of talks. Nauert, speaking at the State Department s daily briefing, insisted that Tillerson was not establishing new policy in his speech, even though he appeared to back away from a key U.S. demand that Pyongyang must first accept that any negotiations would have to be about giving up its nuclear arsenal. ', ' (This version of the story corrects the figure for the current minimum wage to $7.25 from $15 in paragraph two) WASHINGTON (Reuters) - Donald Trump, the presumptive Republican presidential nominee, said on Wednesday he was “open to doing something” with the country’s minimum wage, but added that any increase would have to be weighed against a potential loss of competitiveness. “I’m open to doing something with it,” Trump said in an interview with CNN, adding that he did not like the current $7.25 an hour level. “I mean you have to something that you can live on.” “But what I really do like is bring our jobs back, so they’re making much more than the 15 dollars” an hour, he added. ', 'WASHINGTON (Reuters) - New Jersey Governor Chris Christie, an early supporter of U.S. President-elect Donald Trump, is considering a run to lead the Republican National Committee, Politico reported on Thursday. Reuters could not immediately confirm the report, and representatives for Christie did not immediately respond to a request for comment.  Christie, whose term as governor ends in January 2018, had been leading Trump’s transition team until U.S. Vice President-elect Mike Pence recently took over earlier this month. Current RNC Chairman Reince Priebus has been tapped to serve as Trump’s chief of staff when he starts his White House term Jan. 20, 2017. Christie had launched a presidential bid alongside Trump in a pool of 17 candidates that eventually saw Trump, a New York businessman who had never held political office, win the nomination as well as the Nov. 8 presidential election over Democrat Hillary Clinton.  Christie had been a rising political star before the so-called “Bridgegate” scandal involving his former top aides that left his reputation in tatters.   Pence took over from Christie, who at one time had been considered a possible candidate to serve as Trump’s attorney general, a post that instead went to U.S. Senator Jeff Sessions of Alabama. Trump’s team has said Christie would remain as vice chair of the transition effort. Earlier this month, Christie’s two former aides were convicted for shutting down access l

In [ ]:
!pip install num2words > /dev/null

In [ ]:
from num2words import num2words
import re

def convert_digits(sentence):
    # expression régulière pour trouver les nombres et les ordinaux (1st, 2nd, etc.)
    pattern = r'\d+(st|nd|rd|th)?'

    # fonction pour remplacer chaque nmbr trouvé
    def change_match(m):
        value = m.group()

        # vérifier nmbr est un ordinal
        check_ord = re.match(r'(\d+)(st|nd|rd|th)', value)
        if check_ord:
            n = int(check_ord.group(1))
            word = num2words(n, to="ordinal")
        else:
            n = int(value)
            word= num2words(n)
        return word

    # remplacer tous les nombres dans phrase
    updated_sentence = re.sub(pattern, change_match, sentence)
    return updated_sentence

In [ ]:
numbers_vocab = {
    "zero","one","two","three","four","five","six","seven","eight","nine",
    "ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen",
    "seventeen","eighteen","nineteen","twenty","thirty","forty","fifty",
    "sixty","seventy","eighty","ninety","hundred","thousand",
    "first","second","third","fourth","fifth","sixth","seventh","eighth","ninth","tenth",
}

def drop_stopwords(phrase):

    # tokenisation avec spacy
    doc = nlp(phrase)

    tokens = list(doc)
    result = []
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        # garder le mot si n'est pas stop word ou si c'est un mot de nmbr
        if (not tok.is_stop) or (tok.text.lower() in numbers_vocab):

            # lemmatisation + minuscule
            result.append(tok.lemma_.lower())
        i += 1
    return " ".join(result)

In [ ]:
!pip install contractions

Requirement already satisfied: contractions in /usr/local/lib/python3.12/dist-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in /usr/local/lib/python3.12/dist-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in /usr/local/lib/python3.12/dist-packages (from textsearch>=0.0.21->contractions) (0.3.3)
Requirement already satisfied: pyahocorasick in /usr/local/lib/python3.12/dist-packages (from textsearch>=0.0.21->contractions) (2.3.0)

In [ ]:
def dropunctuation(phrase):
    #tokenisation avec spacy
    doc = nlp(phrase)
    tokens = list(doc)
    cleaned_tok = []

    i = 0
    while i < len(tokens):
        tok = tokens[i]

        # ignorer la ponctuation et les espaces
        if (not tok.is_punct) and (not tok.is_space):
            cleaned_tok.append(tok)
        i += 1
    return cleaned_tok

In [ ]:
processed_texts = []

i = 0
while i < len(X):

    phrase = X[i]
    phrase = phrase.lower()
    phrase = convert_digits(phrase)
    phrase = drop_stopwords(phrase)
    phrase = dropunctuation(phrase)
    processed_texts.append(phrase)

    i += 1
print(processed_texts)
print(type(processed_texts[0]))
print(type(processed_texts))

[[twenty, first, century, wire, say, ben, stein, reputable, professor, pepperdine, university, hollywood, fame, appear, tv, show, film, ferris, bueller, s, day, provocative, statement, judge, jeanine, pirro, s, recently, discuss, halt, impose, president, trump, s, executive, order, travel, stein, refer, judgement, ninth, circuit, court, washington, state, coup, d, tat, executive, branch, constitution, stein, go, judge, seattle, political, puppet, judiciary, political, pawn, watch, interview, complete, statement, note, stark, contrast, rhetoric, leftist, medium, pundit, neglect, note, court, block, presidential, order, immigration, past, discuss, legal, efficacy, halt, actual, text, executive, order.read, trump, news, twenty, first, century, wire, trump, filessupport, work, subscribe, member, @twenty, onewire.tv], [washington, reuters, u.s, president, donald, trump, remove, chief, strategist, steve, bannon, national, security, council, wednesday, reverse, controversial, decision, early, year, political, adviser, unprecedented, role, security, discussion, trump, overhaul, nsc, confirm, white, house, official, elevate, general, joseph, dunford, chairman, joint, chief, staff, dan, coats, director, national, intelligence, head, seventeen, u.s, intelligence, agency, official, say, change, move, nsc, core, function, suppose, appear, mark, victory, national, security, adviser, h.r, mcmaster, tell, national, security, expert, feel, battle, death, bannon, white, house, staff, vice, president, mike, pence, say, bannon, continue, play, important, role, policy, play, shake, routine, natural, evolution, ensure, national, security, council, organize, way, well, serve, president, resolve, make, difficult, decision, pence, say, fox, news, bannon, say, statement, succeed, return, nsc, traditional, role, coordinate, foreign, policy, run, cite, president, barack, obama, national, security, adviser, susan, rice, advocate, change, susan, rice, operationalize, nsc, administration, nsc, ensure, de, operationalized, general, mcmaster, nsc, proper, function, say, trump, white, house, team, grapple, infighting, intrigue, hobble, young, presidency, recent, day, senior, u.s, foreign, policy, national, security, official, say, mechanism, shape, trump, administration, response, press, challenge, syria, north, korea, iran, place, critic, bannon, role, nsc, say, give, weight, decision, making, lack, foreign, policy, expertise, bannon, chief, executive, trump, presidential, campaign, month, lead, election, november, respect, represent, trump, america, first, nationalistic, voice, help, fuel, anti, washington, fervor, push, president, way, time, mainstream, republican, join, trump, administration, bannon, head, breitbart, news, right, wing, website, u.s, representative, adam, schiff, rank, democrat, house, representatives, intelligence, committee, call, shift, nsc, positive, step, help, mcmaster, gain, control, body, politicize, bannon, involvement, administration, policy, north, korea, china, russia, syria, continue, drift, hope, shake, bring, level, strategic, vision, body, say, bannon, removal, nsc, potential, setback, sphere, influence, trump, white, house, voice, major, decision, trump, confidant, say, bannon, remain, influential, involve, confidence, president, fair, stuff, confidant, say, speak, condition, anonymity, white, house, official, say, bannon, long, need, nsc, departure, trump, first, national, security, adviser, michael, flynn, flynn, force, resign, feb, thirteen, contact, russia, ambassador, united, states, sergei, kislyak, prior, trump, take, office, jan, twenty, official, say, bannon, place, nsc, originally, check, flynn, attend, one, nsc, regular, meeting, official, dismiss, question, power, struggle, bannon, mcmaster, say, share, world, view, two, current, national, security, official, reject, white, house, explanation, note, two, month, pass, flynn, departure, mcmaster, say, speak, condition, anonymity, duel, bannon, direct, access, trump, future, deputy, national, security, adviser, k.t, mcfarland, fox, news, commentator, intelligence, director, ezra, cohen, watnick, flynn, appointee, staffing, decision, trump, prepare, first, face, face, meeting, thursday, friday, chinese, president, xi, jinping, threat, north, korea, nuclear, missile, program, key, component, talk, bannon, seat, nsc, principal, committee, group, include, secretary, state, defense, ranking, aide, take, rick, perry, energy, secretary, charge, oversee, u.s, nuclear, weapon, arsenal], [reuters, puerto, rico, governor, ricardo, rossello, say, wednesday, expect, federal, government, waive, jones, act, lift, restriction, ship, provide, aid, island, devastate, hurricane, maria, say, speak, member, congress, party, support, emergency, waiver, expect, waive, rossello, say, interview, cnn, note, seven, day, waiver, hurricane, irma, devastating, island, tuesday, trump, administration, say, need, waive, shipping, restriction, help, fuel, supply, storm, ravage, puerto, rico, say, address, island, damage, port, main, impediment, shipping, waiver, allow, puerto, rico, help, u.s, ship, ship, bring, aid, critical, particularly, fuel, say, one, consideration, right, priority, get, fuel, diesel, gasoline, island, right, fuel, limit, transportation, logistic, point, course, get, fuel, island, go, critical, major, function, telecom, hospital, water, run, appropriately, jones, act, require, good, ship, u.s, port, carry, american, own, operate, ship, u.s, senator, john, mccain, ask, acting, department, homeland, security, secretary, elaine, duke, tuesday, grant, emergency, waiver, law, say, puerto, rican, resident, pay, twice, food, drink, water, supply, waiver, correct, version, story, fix, paragraph, four, administration, formally, deny, waiver, request], [monday, donald, trump, embarrass, country, accidentally, reveal, source, extremely, classified, information, leak, russia, early, month.while, speculate, source, information, israel, trump, thing, crystal, clear, press, conference, prime, minister, benjamin, netanyahu, president, pussygrabber, explain, say, israel, conversation, russian, recipient, leak, information, single, time, understand, mention, word, israel, trump, say, mention, conversation, say, trump, say, gesture, reporter, story, wrong, mention, word, israel, say, word, israel, accord, report, israeli, intelligence, official, shout, counterpart, leak, information.now, accidentally, purpose, confirm, come, from.watch, happen, president, trump, say, mention, word, israel, oval, office, meeting, russian, official, https://t.co/eighty-fourzcwsixty-fourhce, cnn, politics, @cnnpolitics, twenty, two, two, thousand, seventeenfeatured, image, screengrab], [glasgow, scotland, reuters, u.s, presidential, candidate, abroad, sharpen, foreign, policy, credential, donald, trump, arrive, scotland, friday, reopen, golf, resort, presumptive, republican, nominee, seventy, visit, family, ancestral, homeland, showcase, far, fling, business, empire, mother, bear, scotland, isle, lewis, throng, reporter, watch, dramatic, arrival, helicopter, seaside, trump, turnberry, resort, schedule, news, conference, ninth, hole, noon, seven, a.m., et, one, thousand, one, hundred, gmt, visit, turnberry, follow, stop, resort, aberdeen, saturday, allow, comment, outcome, britain, vote, thursday, remain, european, union, think, open, golf, resort, get, foreign, policy, chop, say, saul, anuzis, chairman, michigan, republican, party, right, middle, eu, vote, end, pr, bonanza, risk, real, estate, tycoon, hold, public, office, rate, unfavorably, seventy, percent, americans, opinion, poll, foreign, policy, misstep, time, republican, leader, urge, demeanor, trump, say, incline, leave, eu, exchange, insult, british, prime, minister, david, cameron, call, new, yorker, anti, immigrant, policy, idea, divisive, wrong, plan, two, meet, trip, baffle, republican, official, concentrate, strengthen, campaign, take, fight, presumptive, democratic, nominee, u.s, secretary, state, hillary, clinton, sixty, eight, trump, defeat, crowded, field, opponent, republican, nomination, face, one, controversy, late, firing, campaign, manager, week, month, party, convention, campaign, get, kind, grow, pain, sense, spend, kind, time, go, country, say, david, yepsen, director, paul, simon, public, policy, institute, southern, illinois, university, turnberry, storied, course, open, championship, stag, four, time, trump, invest, $, two, hundred, ninety, million, renovate, resort, golf, course, scotland, west, coast, eighty, five, km, fifty, three, mile, southwest, glasgow, portray, determination, build, course, turnberry, aberdeen, overcome, local, opposition, example, type, leadership, skill, americans, win, white, house, nov, eight, scotland, win, united, states, trump, write, column, press, journal, newspaper, aberdeen, aberdeen, family, oppose, development, threaten, raise, mexican, flag, reminder, proposal, build, wall, u.s, southern, border, immigrant, enter, illegally, republican, presidential, nominee, massachusetts, governor, mitt, romney, two, thousand, twelve, gaffe, fill, campaign, trip, london, jerusalem, poland], [wednesday, democrats, take, powerful, stance, gop, s, refusal, vote, gun, control, measure, stag, sit, republican, politician, call, recess, take, lunch, break, dem, stayed, floor, fight, safety, america, s, citizens.hour, sit, house, speaker, paul, ryan, weigh, event, interview, cnn, comment, disappointing, disgusting, response, sit, follow, death, fifty, innocent, americans, lose, life, tragic, mass, shooting, orlando, week, ago, brutal, sentence, publicity, stunt, seriously, genuine, attempt, congress, support, gun, control, measure, protect, american, citizen, senseless, gun, violence, like, mass, shooting, consider, publicity, stunt, lead, republican, speaker, house, add, democrats, involve, sit, try, rob, americans, right, insist, focus, gun, control, real, threat, terrorism, say, ryan, completely, ignore, fact, mass, shooting, united, states, zero, connection, terrorism, cause, individual, able, hand, gun, effortlessly.to, prove, backwards, ryan, s, logic, accuse, hard, work, democrat, fight, gun, control, legislation, sit, attention, instead, create, solution, clearly, forget, gop, colleague, eat, lunch, happen, definitely, doesn, t, solve, wolf, blitzer, ask, ryan, nra, major, obstacle, stand, way, gun, control, legislation, ryan, say, constitution, americans, guarantee, second, amendment, right, firearms.you, watch, ryan, s, horrific, comment, entire, interview, infuriate, truly, prove, gop, care, gun, americans, right, safety.feature, image, allison, shelley, getty, image], [president, trump, s, rally, fl, saturday, smashing, success, nine, thousand, crowding, hanger, hear, speak, two, three, time, congregate, outside.trump, tell, supporter, want, speak, filter, fake, news, warm, act, president, trump, s, speech, youtube, sensation, diamond, silk, fire, crowd.diamond, silk, let, medium, let, didn, t, believe, primary, didn, t, believe, general, election, read, lip, don, t, believe, diamond, silk, message, medium, @realdonaldtrump, melbourne, fl, rally, pic.twitter.com/threebfiveufouruubto, kristinn, taylor, @kristinnfr, february, eighteen, two, thousand, seventeenme, favorite, deplorable, @diamondandsilk, melbourne, trumprally, trumptrain, pic.twitter.com/cwtwormiiohu, cory, trump, two, thousand, twenty, @livelifecorazy, february, eighteen, two, thousand, seventeen(source, gateway, pundit], [s, europe, s, version, outspoken, ted, cruz, time, nigel, farage, leader, uk, independence, party, disliked, member, european, parliment, plow, ahead, ignorne, open, sneer, insult, fellow, member, eu, parliment, count, bad, piece, public, policy, see, modern, europe, half, century, compound, fail, flaw, eu, common, asylum, policy, say, world, come, europe, see, frankly, virtually, stampede, learn, eighty%, come, syrian, refugee, fact, ve, open, door, young, male, economic, migrant, behave, aggressive, manner, opposite, expect, refugee, failure, meet, objection, country, like, hungary, opinion, crush, isn, t, europe, peace, s, europe, division, s, europe, disharmony, s, europe, s, recipe, resentment, face, failure, say, thing, today, say, europe, isn, t, work, let, s, europe, failing, think, bright, star, horizon, s, call, british, referendum, give, want, concede, britain, ability, control, border, brexit, look, likely, time, use, one, hundred, nigel, farage, s, u.s, congress, .https://youtu.be/gbjpeightzxduwk], [washington, reuters, state, department, say, wednesday, united, states, open, talk, north, korea, time, right, happen, pyongyang, show, sign, willingness, halt, missile, nuclear, testing, despite, u.s, secretary, state, rex, tillerson, s, offer, tuesday, start, talk, north, korea, pre, condition, state, department, spokeswoman, heather, nauert, say, first, period, calm, pyongyang, suspend, testing, negotiation, begin, tillerson, speech, washington, think, tank, tuesday, explicitly, establish, freeze, requirement, north, korea, meet, ahead, talk, nauert, speak, state, department, s, daily, briefing, insist, tillerson, establish, new, policy, speech, appear, away, key, u.s, demand, pyongyang, first, accept, negotiation, give, nuclear, arsenal], [version, story, correct, figure, current, minimum, wage, $, seven.twenty, five, $, fifteen, paragraph, two, washington, reuters, donald, trump, presumptive, republican, presidential, nominee, say, wednesday, open, country, minimum, wage, add, increase, weigh, potential, loss, competitiveness, open, trump, say, interview, cnn, add, like, current, $, seven.twenty, five, hour, level, mean, live, like, bring, job, make, fifteen, dollar, hour, add], [washington, reuters, new, jersey, governor, chris, christie, early, supporter, u.s, president, elect, donald, trump, consider, run, lead, republican, national, committee, politico, report, thursday, reuter, immediately, confirm, report, representative, christie, immediately, respond, request, comment, christie, term, governor, end, january, two, thousand, eighteen, lead, trump, transition, team, u.s, vice, president, elect, mike, pence, recently, take, early, month, current, rnc, chairman, reince, priebus, tap, serve, trump, chief, staff, start, white, house, term, jan, twenty, two, thousand, seventeen, christie, launch, presidential, bid, alongside, trump, pool, seventeen, candidate, eventually, see, trump, new, york, businessman, hold, political, office, win, nomination, nov, eight, presidential, election, democrat, hillary, clinton, christie, rise, political, star, call, bridgegate, scandal, involve, aide, leave, reputation, tatter, penny, take, christie, one, time, consider, possible, candidate, serve, trump, attorney, general, post, instead, go, u.s, senator, jeff, sessions, alabama, trump, team, say, christie, remain, vice, chair, transition, effort, early, month, christie, two, aide, convict, shut, access, lane, george, washington, bridge, two, thousand, thirteen, create, day, long, traffic, jam, scheme, intend, punish, town, mayor, democrat, decline, endorse, christie, reelection, campaign], [], [paris, reuters, france, germany, agree, iran, reverse, ballistic, missile, program, end, hegemonic, temptation, middle, east, french, foreign, minister, say, monday, view, necessity, iran, ballistic, missile, program, hegemonic, temptation, jean, yve, le, drian, say, news, conference, alongside, german, counterpart, sigmar, gabriel], [brussels, reuters, martin, selmayr, aide, head, european, commission, jean, claude, juncker, signal, friday, agreement, britain, s, divorce, term, eu, tweet, picture, white, smoke, symbol, election, new, pope, juncker, selmayr, eu, s, chief, brexit, negotiator, michel, barnier, work, breakfast, british, prime, minister, theresa, brussels], [blame, trump, compassionate, ask, middle, eastern, country, open, arm, fellow, male, muslim, world, community, demand, compassion, citizen, government, majority, muslim, country, right, door, syria, donald, trump, say, send, home, syrian, refugee, accept, president.the, billionaire, current, frontrunner, republican, race, white, house, tell, new, hampshire, rally, win, go, mark, reversal, policy, early, month, tell, fox, news, refugees.a, migrant, crisis, grip, part, europe, pledge, ten, zero, refugee, syria, year.half, million, people, cross, mediterranean, europe, two, thousand, fifteen, large, number, syria, two, hundred, fifty, zero, people, kill, civil, war.on, wednesday, night, mr, trump, tell, audience, keene, high, school, hear, want, two, hundred, zero, syrians, listen, isis, islamic, state, describe, two, hundred, zero, man, army, later, add, m, put, people, notice, come, syria, mass, migration, win, win, go, ask, think, migrant, travel, europe, allow, business, mogul, say, hate, concept, humanitarian, basis, s, happen, blame, president, barack, obama, crisis, add, s, live, hell, syria, live, hell], [vientiane, reuters, united, states, announce, tuesday, provide, additional, $, ninety, million, three, year, help, laos, heavily, bomb, vietnam, war, clear, unexploded, ordnance, kill, injure, twenty, zero, people, figure, announce, president, barack, obama, first, visit, laos, close, $, one, hundred, million, united, states, spend, past, twenty, year, clear, uxo, laos, one, thousand, nine, hundred, sixty, four, one, thousand, nine, hundred, seventy, three, u.s, warplane, drop, two, hundred, seventy, million, cluster, munition, communist, country, one, third, explode, lao, national, regulatory, authority, uxo, say, obama, first, u.s, president, visit, laos, arrive, isolate, country, monday, attend, two, regional, summit, half, century, america, secret, war, leave, laos, unfortunate, distinction, heavily, bomb, country, capita, history, white, house, say, statement, u.s, program, laos, help, slash, uxo, casualty, three, hundred, fifty, year, additional, funding, comprehensive, uxo, survey, laos, continued, clearing, operation, united, states, help, laos, clear, unexploded, ordnance, pose, threat, people, hamper, economic, development, say, package, help, support, uxo, victim, need, rehabilitation, include, orthotic, prosthetic, add, obama, speech, tuesday, capital, vientiane, address, secret, war, result, conflict, people, flee, drive, home, obama, say, time, america, acknowledge, role, believe, united, states, moral, obligation, help, laos, heal, uxo, remain, stubborn, problem, region, expert, decade, clear, landmine, bomb, laos, cambodia, vietnam, beset, conflict, one, thousand, nine, hundred, sixtys, one, thousand, nine, hundred, seventys, cambodia, case, one, thousand, nine, hundred, eightys, one, thousand, nine, hundred, ninety, central, lao, province, xieng, khouang, area, heavily, bomb, u.s, aircraft, war, neighboring, vietnam, trail, devastation, eighty, percent, people, landlocke, laos, rely, agriculture, simply, dangerous, farm, approximately, quarter, village, contaminate, unexploded, ordnance, say, british, base, mine, advisory, group, help, find, destroy, bomb, wednesday, obama, expect, visit, organization, vientiane, work, disabled, unexploded, ordnance, cooperative, orthotic, prosthetic, enterprise, visitor, center], [judge, right, determine, mother, father, name, child, don, t, think, one, minute, politically, correct, environment, live, couldn, t, happen, right, united, states, name, bizarre, t, believe, ve, give, child, recent, landmark, case, go, step, tell, mother, t, newborn, twin, name, chose.the, mother, powys, wale, attempt, offspring, cyanide, preacher, believe, cyanide, pretty, little, girl, positive, implication, s, poison, kill, hitler, follower, joseph, goebbel, accord, metro, argue, right, child, justice, eleanor, king, rule, cause, emotional, harm, child, future, hard, twin, girl, regard, name, deadly, poison, complete, rejection, birth, mother, say, king.the, twin, eight, month, old, reportedly, conceive, rape, place, fost

In [ ]:
# ensemble pour stocker les mots uniques
vocab_set = set()
for phrases in processed_texts:
    tokens = list(phrases)
    for tok in tokens:
        # minuscule pour eviter doublons
        vocab_set.add(tok.text.lower())

# trier le vocabulaire
vocab_list = sorted(vocab_set)
# construire le vocabulaire apres le traitement du texte
print("Vocabulary:", vocab_list)
print(len(vocab_list))

Vocabulary: ['$', '+', '-andrew', '-independentthe', '-nineteen', '-one', '-or-', '-robert', '.@realdonaldtrump', '.@rkadyrov', '.brat', '.cnn', '.dure', '.forty', '.here', '.how', '.https://youtu.be/gbjpeightzxduwk', '.i', '.in', '.more', '.now', '.source', '.spxrt', '.the', '.viewer', '.watch', '.with', '//connect.facebook.net', '<', '=', '@aaldef', '@abc', '@abcpolitics', '@advodude', '@alpunto', '@alxthomp', '@andrewchamings', '@angelojohngage', '@antoniodelotero', '@babyboogaloo', '@barbmuenchen', '@beyonce', '@biancaamarilis', '@billmaher', '@billstl', '@blisstabitha', '@blob_fish', '@boycotkochbro', '@braddjaffy', '@brfreed', '@bttrcrmbakeshop', '@buzzfeedandrew', '@carlbernstein', '@carminezozzora', '@cbs', '@cbsnews', '@cernovich', '@chriscuomo', '@cnn', '@cnnpolitics', '@collinrugg', '@comebackteamtwelve', '@cooksphere', '@corrynmb', '@culturalcombat', '@dan_gartland', '@dankbeans', '@davidgmcafee', '@davidmackau', '@davisonvideo', '@diamondandsilk', '@disneymommytwenty', '@duff_goldman', '@eaglesjesse', '@elizabethforma', '@fakeezralevant', '@flyosity', '@foxandfriend', '@foxandfriends', '@foxbusiness', '@foxnews', '@gavin_mcinnes', '@glennbeck', '@gop', '@green_footballs', '@hardball', '@hillaryclinton', '@housegop', '@humanrightscampaign', '@iamjohnoliver', '@iggyazalea', '@iggys_bitch', '@ike_saul', '@infowars', '@jacobawohl', '@jeniferstevens', '@jessearreguin', '@joeperticone', '@jonfavs', '@jonlovett', '@joshdcaplan', '@kadyrov_ninety', '@kayajones', '@keurig', '@kharyp', '@kristinnfr', '@ksatnews', '@ladyaodh', '@laurenduca', '@livelifecorazy', '@lovelaceryand', '@lrihendry', '@maddowblog', '@marcorubio', '@marcorubiohillary', '@mashable', '@mbglenn', '@mccarthyryanj', '@mepfuller', '@miceemouse', '@michaelbickle', '@michaeljhout', '@mikegarrigantwenty', '@millennialtwo', '@minnysconsin', '@mountain_goats', '@msnbc', '@mtv', '@mysportsupdate', '@nbcnew', '@nbcnews', '@networkjunkyz', '@newday', '@niamagathreex', '@noelle_cd', '@noulaone', '@nra', '@nubianawakening', '@nytime', '@nytimes', '@oldnavy', '@peterbeinart', '@politicalshort', '@potus', '@pourmecoffee', '@r_little_finger', '@realdonaldtrump', '@realjameswoods', '@realtimblack', '@realtimers', '@realvivaeuropa', '@reince', '@reverendmatty', '@rnicaro', '@rogerjstonejr', '@sarahcolonna', '@scottwalk', '@seanhannity', '@seanoconnz', '@senategop', '@shane_bauer', '@shaunking', '@sinow', '@slacksecondefuture', '@speakerryan', '@sreekotay', '@td_port', '@tedcruz', '@the_anti_fox', '@theerimtanangleread', '@thehill', '@thenivenulls', '@thisweekabc', '@timbaffoe', '@timgwthirty', '@tj_knight', '@tvietoreight', '@tweet_dec', '@twenty', '@txintenseradio', '@veevee', '@veteransfourtruth', '@voleighty', '@whiteboyseventhst', '@wsbtv', '@yalelawsch', '@youngdemsfourtrump', 'a$$holes.here', 'a$fifteen', 'a$fifty', 'a$forty', 'a$one', 'a**hole.that', 'a.', 'a.c', 'a.d', 'a.i', 'a.j', 'a.m', 'a.m.', 'a]ppreciate', 'aaja', 'aapl.o', 'aargh', 'aaron', 'aarp', 'ab', 'abadi', 'abandon', 'abbas', 'abbasi', 'abbasid', 'abbie', 'abbott', 'abbottabad', 'abboud', 'abc', 'abd', 'abdel', 'abdessalam', 'abdicate', 'abdomen', 'abdoulaye', 'abdulaziz', 'abdullah', 'abdulrahman', 'abe', 'abedi', 'abedin', 'abel', 'aberdeen', 'abet', 'abi', 'abide', 'abidjan', 'ability', 'abkhazia', 'able', 'abnormally', 'aboard', 'abode', 'abolish', 'abolishment', 'abortion', 'abortion.rep', 'aboul', 'about).sander', 'about.excite', 'about.source', 'above.when', 'abraham', 'abramoff', 'abroad', 'abrupt', 'absence', 'absent', 'absolute', 'absolutely', 'absolve', 'abstain', 'abstention', 'abstract', 'absurd', 'absurdly', 'abu', 'abul', 'abuse', 'abuse.social', 'abuser', 'abusive', 'abusive.recently', 'abysmal', 'aca', 'academic', 'academy', 'accelerate', 'accept', 'acceptable', 'acceptance', 'access', 'accessible', 'accident', 'accidental', 'accidentally', 'accolade', 'accommodate', 'accompany', 'accomplice', 'accomplish', 'accomplishment', 'accord', 'accordance', 'account', 'accountability', 'accountable', 'accuracy', 'accurate', 'accurately', 'accusation', 'accuse', 'accuser', 'acha', 'achieve', 'achievement', 'acknowledge', 'acknowledgement', 'aclu', 'acne', 'acosta', 'acoustic', 'acquire', 'acquisition', 'acquit', 'acr', 'acre', 'acrimonious', 'acronym', 'act', 'act.gorka', 'acting', 'action', 'activate', 'activation', 'active', 'actively', 'activism', 'activist', 'activities.because', 'activity', 'actor', 'actors', 'actress', 'actual', 'actuality', 'actualize', 'actually', 'ad', 'adam', 'adamantly', 'adams', 'adana', 'adapt', 'add', 'added)at', 'added.a', 'added.it', 'added.the', 'addendum', 'addict', 'addicting', 'addictive', 'addition', 'additional', 'additionally', 'address', 'adds.north', 'ade', 'adedayo', 'adele', 'adelson', 'aden', 'adeniyi', 'adequate', 'adequately', 'adhere', 'adjacent', 'adjective', 'adjourn', 'adjust', 'adjustability', 'adjusted', 'adjustment', 'administer', 'administration', 'administration.accorde', 'administration.if', 'administration.of', 'administrative', 'administrator', 'admiral', 'admire', 'admirer', 'admission', 'admit', 'admittedly', 'admitting', 'adolf', 'adopt', 'adoption', 'adoption.we', 'adore', 'adorn', 'adrian', 'adthreemedia', 'adult', 'adultery', 'advance', 'advanced', 'advantage', 'advantageous', 'adventure', 'adverise', 'adversary', 'advertisement', 'advertisement.oh', 'advertiser', 'advertising', 'advice', 'advise', 'adviser', 'advisor', 'advisor.while', 'advisory', 'advocacy', 'advocate', 'advocate.just', 'aerial', 'aerosmith', 'af', 'afar', 'afd', 'affair', 'affairs', 'affect', 'affected', 'affection', 'affection.here', 'affidavit', 'affiliate', 'affiliation', 'affirmation', 'affirmative', 'affleck', 'afflict', 'afford', 'affordable', 'afghan', 'afghanistan', 'afl', 'aflw', 'aforementioned', 'afraid', 'africa', 'african', 'afro.com', 'aftermath', 'afternoon', 'afternoon.the', 'aftershock', 'afterward', 'afzal', 'ag', 'again.according', 'again.take', 'again.watch', 'again?in', 'age', 'aged', 'agency', 'agency.the', 'agenda', 'agenda.steve', 'agent', 'aggravate', 'aggression', 'aggressive', 'aggressively', 'agitated', 'agitator', 'agitprop', 'agne', 'ago', 'ago.after', 'agonize', 'agree', 'agreement', 'agrees.maybe', 'agricultural', 'agriculture', 'agrofert', 'agus', 'ahca', 'ahead', 'ahmar', 'ahmed', 'aid', 'aide', 'aim', 'ain', 'ainsley', 'aipac', 'air', 'airborne', 'aircraft', 'aire', 'airline', 'airplane', 'airport', 'airports', 'airspace', 'airstrike', 'airwave', 'aisle', 'ak', 'aka', 'akhmetshin', 'akpgate', 'al', 'al-', 'al.com', 'alabama', 'alan', 'alarm', 'alarming', 'alaska', 'albeit', 'albert', 'album', 'albuquerque', 'alcohol', 'ald', 'alejandro', 'aleppo', 'alert', 'alex', 'alexander', 'alexandra', 'alexandria', 'alexis', 'alford', 'algier', 'algorithm', 'ali', 'alibaba', 'alien', 'alienate', 'alienated', 'align', 'alike', 'alimony', 'alito', 'alive', 'all.here', 'all.image', 'all.so', 'all.the', 'allah', 'allardbobby', 'allegation', 'allege', 'alleged', 'allegedly', 'allegiance', 'allen', 'allergan', 'alleviate', 'alliance', 'allied', 'allison', 'allot', 'alloush', 'allow', 'allre', 'allude', 'allusion', 'ally', 'almagro', 'alone.the', 'alongside', 'alphabay', 'alphabet', 'already.feature', 'alt-right.while', 'alter', 'altercation', 'alternate', 'alternative', 'altogether', 'alton', 'aluminum', 'alumni', 'alupar', 'alve', 'amal', 'amal.she', 'amateur', 'amazed', 'amazing', 'amazon', 'amazon.com', 'ambassador', 'ambassadorial', 'ambiguity', 'ambiguous', 'ambiguously', 'ambition', 'ambitious', 'ambulance', 'ambush', 'amelia', 'amend', 'amendment', 'amendment.you', 'amenities.specifically', 'america', 'america.and', 'america.ignore', 'america.it', 'america.the', 'america://', 'americafirst', 'american', 'americans', 'americans.noel', 'amherst', 'ami', 'amid', 'amidror', 'amman', 'ammon', 'ammunition', 'amnesty', 'amode', 'amount', 'amplify', 'amputation', 'amy', 'ana', 'anadolu', 'analogy', 'analysis', 'analyst', 'analyze', 'anarchist', 'anastasiade', 'anaya', 'ancestral', 'ancestry', 'anchor', 'anchorman', 'ancient', 'and/or', 'andean', 'anderson', 'andre', 'andrea', 'andrej', 'andrew', 'andrzej', 'andy', 'angel', 'angela', 'angeles', 'angeles.freshmen', 'angelique', 'angelo', 'anger', 'angerer', 'angle', 'angola', 'angolan', 'angolans', 'angry', 'animal', 'animalia', 'anita', 'ankara', 'ankle', 'ann', 'anna', 'anne', 'annette', 'annex', 'annexation', 'annexed', 'annie', 'anniversary', 'announce', 'announcement', 'announcer', 'annoying', 'annual', 'annually', 'annuity', 'annul', 'ano', 'anomaly', 'anonymity', 'anonymous', 'anonymously', 'another.dure', 'ansar', 'ansi', 'answer', 'antagonism', 'antagonistic', 'antarctica', 'anthem', 'anthony', 'anti', 'anti-war.com', 'antibiotic', 'anticipate', 'anticipated', 'anticipation', 'anticonvulsant', 'antifa', 'antifascist', 'antigovernment', 'antiquity', 'antitrust', 'anton', 'antonescu', 'antonin', 'antonio', 'antuam', 'anuzis', 'anwr', 'anxiety', 'anybody', 'anymore', 'anymore.wheth', 'anything.benza', 'anything.feature', 'anytime', 'anyway.and', 'anyway.watch', 'aoun', 'ap', 'apa', 'apache', 'apart', 'apart.now', 'apartment', 'apathy', 'apdal', 'apex', 'apiavote', 'apologist', 'apologize', 'apology', 'appal', 'appalling', 'apparatus', 'apparel', 'apparent', 'apparently', 'apparently.feature', 'appeal', 'appeals', 'appear', 'appearance', 'appetite', 'applaud', 'applause', 'apple', 'applegate', 'applicable', 'application', 'apply', 'appoint', 'appointed.mich', 'appointee', 'appointment', 'appreciate', 'apprehend', 'apprehension', 'apprehensive', 'approach', 'approaching.bin', 'appropriate', 'appropriately', 'appropriation', 'appropriations', 'approval', 'approve', 'approving', 'approximately', 'apratment', 'april', 'apron', 'apvia', 'aqap', 'aqis', 'aqsa', 'ar', 'arab', 'arabia', 'arabia.no', 'arabian', 'arabic', 'arabs', 'arafat', 'arakan', 'aramaic', 'arash', 'arbitrarily', 'arbitrary', 'arcade', 'arcane', 'arch', 'archaeological', 'archaic', 'archeological', 'architect', 'architectural', 'archive', 'arctic', 'ardent', 'ardern', 'ardor', 'are.happy', 'are.hey', 'are.this', 'area', 'aren', 'arena', 'areva', 'argentina', 'arguably', 'argue', 'argument', 'ari', 'arianna', 'ariful', 'arise', 'aristotelian', 'ariz', 'arizona', 'arkansas', 'arlington', 'arm', 'armanatha', 'armed', 'armed?police', 'armenian', 'armin', 'armor', 'arms', 'army', 'army.image', 'arnold', 'arraignment', 'arrange', 'arrangement', 'array', 'arreguin', 'arrest', 'arrest.via', 'arrested.bill', 'arrested.not', 'arrival', 'arrive', 'arrived', 'arrogant', 'arrogantly', 'ars', 'arsa', 'arsenal', 'arson', 'art', 'artfully', 'article', 'articulate', 'artificial', 'artillery', 'artist', 'ary', 'asamblea', 'ascend', 'asean', 'ash', 'ashamed', 'ashcroft', 'asia', 'asian', 'asianamericanlegal', 'asians', 'aside', 'asinine', 'ask', 'asked.co', 'asked.felarca', 'asking', 'asleep', 'aspect', 'aspiration', 'aspire', 'ass', 'assad', 'assail', 'assailant', 'assange', 'assasinate', 'assassinate', 'assassination', 'assassination.mr', 'assault', 'assemble', 'assembly', 'assemblywoman', 'assert', 'assertion', 'assess', 'assesse', 'assessment', 'assessment.the', 'asset', 'asshole', 'assignment', 'assimilate', 'assimilation', 'assist', 'assistance', 'assistant', 'associate', 'associated', 'association', 'associations.national', 'assorted', 'assume', 'assumption', 'assurance', 'assurance.i', 'assure', 'assyrian', 'astana', 'astonishment', 'astounding', 'astronomically', 'astroturfe', 'asylum', 'asz', 'at&t', 'atheist', 'athens', 'athlete', 'athletic', 'athletics', 'atlanta', 'atlantic', 'atmosphere', 'atms', 'atomic', 'atop', 'atrocity', 'attach', 'attack', 'attack.for', 'attack.watch', 'attacker', 'attacks.by', 'attacks.he', 'attacks.whether', 'attain', 'attempt', 'attend', 'attendance', 'attendant', 'attendee', 'attention', 'attention.politifact', 'attentive', 'attest', 'attitude', 'attorney', 'attract', 'attraction', 'attractive', 'attributable', 'attribute', 'attribution', 'audacity', 'audience', 'audio', 'audit', 'auditor', 'auditorium', 'aug', 'august', 'aung', 'auspex', 'austin', 'australia', 'australian', 'australians', 'austrian', 'authentic', 'authenticity', 'author', 'authorise', 'authoritarian', 'authorities.daryl', 'authorities.the', 'authority', 'authorization', 'authorize', 'auto', 'autocracy', 'autograph', 'automaker', 'automate', 'automatically', 'automobile', 'automotive', 'autonomous', 'autonomy', 'autoplex', 'autopsy', 'autumn', 'avail', 'availability', 'available', 'avalanche', 'avenue', 'average', 'aviation', 'avidity', 'aviv', 'avoid', 'avoidance', 'await', 'awake', 'awaken', 'awakening', 'award', 'aware', 'awareness', 'away', 'away.a', 'away.my', 'awe', 'awesome', 'awful', 'awkward', 'awkwardly', 'awry', 'axiomatic', 'axios', 'ayatollah', 'aydaroos', 'ayrault', 'azalea', 'azerbaijan', 'b', 'b.', 'ba.n', 'baba.n', 'babble', 'babi', 'babis', 'baby', 'babylonian', 'bac.n', 'bachelet', 'bachelor', 'back', 'back.-', 'back.trump', 'back.we', 'backbone', 'backdoor', 'backdrop', 'backer', 'backfire', 'background', 'backgrounds.one', 'backhand', 'backing', 'backlash', 'backpack', 'backstage', 'backtrack', 'backup', 'backwards', 'bacteria', 'bacteria.all', 'bad', 'baden', 'badge', 'badly', 'baffle', 'bag', 'baggage', 'baggari', 'baghdad', 'baghdadi', 'bahr', 'bahrain', 'baier', 'bail', 'bailey', 'bailout', 'bait', 'baiter', 'bajaur', 'bajwa', 'bake', 'baker', 'bakeshop', 'bakken', 'bakour', 'bakr', 'balance', 'balanced', 'balangiga', 'balart', 'balcony', 'balderston', 'baldwin', 'balint', 'balk', 'balkan', 'ball', 'baller', 'ballistic', 'balloon', 'ballot', 'ballpark', 'balmy', 'baltic', 'baltimore', 'balukhali', 'bamn', 'ban', 'bana', 'banana', 'band', 'bandana', 'bandito', 'bang', 'banging', 'bangladesh', 'bangladeshi', 'bank', 'banker', 'banking', 'bankruptcy', 'banner', 'bannon', 'baptist', 'baqaa', 'bar', 'barack', 'barb', 'barbara', 'barbaric', 'barbarism.seven', 'barbarity', 'barcelona', 'barely', 'barfly', 'bargaining', 'baris', 'barkin', 'barnaby', 'barnette', 'barney', 'barnier', 'baron', 'barrage', 'barricade', 'barrier', 'barron', 'barry', 'barton', 'barzani', 'basalla', 'basalt', 'base', 'baseball', 'based?your', 'bash', 'bashar', 'basic', 'basically', 'basis', 'baskaya', 'basket', 'basketball', 'basketofdeplorable', 'bass', 'bastard', 'batarfi', 'batch', 'bate', 'bathroom', 'bathroom.the', 'baton', 'battered', 'battery', 'battle', 'battlefield', 'battleground', 'batts', 'bauer', 'bay', 'bayer', 'bazar', 'bbc', 'bbcone', 'bce', 'beach', 'beacon', 'beam', 'bear', 'bearer', 'bearing', 'beat', 'beaten.watch', 'beating', 'beatle', 'beautiful', 'beauty', 'bechtel', 'beck', 'beckham', 'beckon', 'becky', 'bed', 'bed.on', 'bedroom', 'bedroom.neither', 'bedside', 'beef', 'been.aren', 'beer', 'befall', 'before.in', 'before.trump', 'beg', 'begin', 'beginning', 'begun.high', 'behalf', 'behar', 'behave', 'behavior', 'behead', 'beheading', 'behemoth', 'behest', 'behind.outside', 'behrouz', 'beijing', 'beijing.the', 'beinart', 'being', 'beings.very', 'beirut', 'beit', 'bela', 'belarus', 'belgian', 'belgium', 'belhadj', 'belief', 'believe', 'bell', 'belligerent', 'bellwether', 'belong', 'belonging', 'beloved', 'below.https://www.facebook.com/attnvideo/videos/one', 'below.obama', 'below:.@realdonaldtrump', 'belt', 'beltway', 'ben', 'bench', 'bend', 'beneath', 'benedict', 'beneficial', 'beneficiary', 'benefit', 'benghazi', 'benghazi.burie', 'benjamin', 'bennelong', 'benner', 'bennett', 'bent', 'benz', 'benza', 'beppe', 'ber', 'berhad', 'berkeley', 'berlin', 'berman', 'bernardino', 'bernice', 'bernie', 'bernstein', 'beset', 'besiege', 'bespoke', 'best', 'bestiality', 'bestow', 'bestseller', 'bet', 'bethlehem', 'betray', 'betsy', 'betty', 'between~', 'beverly', 'bevy', 'beware', 'bey', 'beyer', 'beyonc', 'beyonce', 'bharatiya', 'bi', 'bianca', 'bias', 'biased', 'bibi', 'bible', 'biblical', 'bickering', 'bickle', 'bid', 'bidding', 'biden', 'bie', 'biennial', 'big', 'biggie', 'bigot', 'bigoted', 'bigotry', 'biker', 'bilah', 'bilateral', 'bilaterally', 'bild', 'bilil', 'bill', 'bill.-inforum', 'bill.feinstein', 'bill.sen', 'billboard', 'billion', 'billionaire', 'bin', 'binali', 'binary', 'bind', 'binding', 'binge', 'bio', 'biographer', 'bipartisan', 'bird', 'birth', 'birthday', 'birthplace', 'bisexual', 'bit', 'bit.ly/twenty-eightusevencaseven', 'bit.ly/twoiktwojqp', 'bitch', 'bitcoin', 'bite', 'bitter', 'bitterly', 'biz', 'bizarre', 'bizarrely', 'bjp', 'black', 'blackhawk', 'blacklist', 'blacklive', 'blackout', 'blackriflecoffee', 'blackstone', 'blacktracke', 'bladder', 'blah', 'blair', 'blame', 'blame.feature', 'blaming', 'blank', 'blasio', 'blasphemy', 'blast', 'blatant', 'blatantly', 'blaze', 'bleed', 'blessing', 'blind', 'blindly.but', 'blindside', 'blistering', 'blitzer', 'blm', 'bloated', 'bloc', 'block', 'blockade', 'blockbuster', 'blog', 'blood', 'bloodlust', 'bloodshe', 'bloody', 'bloomberg', 'blow', 'blowback', 'blu', 'bludgeon', 'blue', 'bluelivesmatter', 'blueprint', 'blumenauerlisa', 'blumenthal', 'blunt', 'blur', 'blurt', 'bmw', 'bmwg.de', 'boa', 'board', 'boast', 'boasted.aside', 'boat', 'bob', 'bobby', 'bodily', 'body', 'boehner', 'boeing', 'boente', 'bog', 'bogge', 'bogus', 'bohemia', 'bohemian', 'bohuslav', 'boiler', 'boilerplate', 'bold', 'bolduan', 'bolivar', 'bollard', 'bollinger', 'bolster', 'bolt', 'bomb', 'bomber', 'bombing', 'bona', 'bonamicirobert', 'bonanza', 'bond', 'bone', 'bonus.#boycottkeurig#istandwithhannity#buyblackriflecoffee#maga', 'boo', 'boochani', 'book', 'boom', 'boon', 'boost', 'boot', 'booth', 'border', 'borderland', 'borderline', 'boris', 'borne', 'borneo', 'borrower', 'bosnia', 'bosnian', 'boss', 'bossier', 'bossy', 'boston', 'boston.com', 'bostonfreespeechrally', 'bosworth', 'bot', 'botched', 'bother', 'botox', 'bottle', 'bottom', 'bounce', 'bound', 'boundary', 'bow', 'bowl', 'bowle', 'bowman', 'box', 'boxing', 'boy', 'boycott', 'boycottkeurig', 'boycotts', 'boyd.these', 'boys.and', 'boysie', 'bozanovici', 'bra', 'brace', 'brad', 'bradd', 'bradshaw', 'brady', 'bradyanthony', 'brag', 'brain', 'brainer', 'brainwash', 'branch', 'branch.i', 'branches.expert', 'brand', 'brandy', 'branko', 'bras', 'brash', 'brasileiras', 'brasilia', 'brat', 'braun', 'brava', 'bravado', 'brave', 'bravo!feature', 'bravo!we', 'brawl', 'brazen', 'brazenly', 'brazil', 'brazilian', 'breach', 'bread', 'break', 'breakaway', 'breakdown', 'breaker', 'breakfast', 'breaking', 'breakneck', 'breath', 'breathe', 'breathing', 'breathing.little', 'breed', 'breeding', 'breitbart', 'brekken', 'brenda', 'brennan', 'bret', 'brett', 'brewer', 'brexit', 'brian', 'brianna', 'bribe', 'brick', 'bridge', 'bridgegate', 'bridges', 'brief', 'briefing', 'briefing.the', 'briefingi', 'briefly', 'brien', 'brigade', 'bright', 'bright.not', 'brilliance', 'brilliant', 'brilliant.feature', 'brilliantly', 'bring', 'brink', 'bristol', 'britain', 'british', 'britta', 'broach', 'broad', 'broadcast', 'broadcaster', 'broadcasting', 'broaden', 'broadening', 'broadly', 'brochure', 'brock', 'broken', 'broker', 'brooke', 'brooking', 'brother', 'brotherhood', 'brotherly', 'brouhaha', 'browbeat', 'brown', 'brownback', 'brownfield', 'brownmichael', 'bruce', 'bruise', 'brunei', 'bruni', 'bruno', 'brunswick', 'brush', 'brussels', 'brutal', 'brutality', 'brutally', 'bryant', 'bs', 'bso', 'btw', 'bubble', 'buchar', 'bucharest', 'buckle', 'budapest', 'buddhist', 'buddy', 'budge', 'budget', 'bueller', 'buenos', 'buff', 'buffoon', 'build', 'builder', 'building', 'building.please', 'buildings.image', 'bulent', 'bulgaria', 'bulgarian', 'bulk', 'bull', 'bullet', 'bullet!in', 'bullhorn', 'bullseye', 'bullsh*t', 'bullsh*t.however', 'bullshit', 'bully', 'bullying', 'bumble', 'bumper', 'bumpy', 'bunch', 'bundy', 'bungle', 'bunker', 'burden', 'burdensome', 'bureau', 'bureaucracy', 'bureaucrat', 'burgeon', 'burger', 'burkina', 'burma', 'burmese', 'burn', 'burning', 'burr', 'bursa', 'burst', 'burundi', 'bury', 'bus', 'bush', 'bush.john', 'business', 'businessman', 'bust', 

In [ ]:
bow_vectors = []
for phrase in processed_texts:
    vec = [0] * len(vocab_list)

    for tok in phrase:
        if tok.text.lower() in vocab_list:
            index = vocab_list.index(tok.text.lower())
            vec[index] = 1

    bow_vectors.append(vec)

In [ ]:
import numpy as np

X_vectors = np.array(bow_vectors) #define your Vectors
y_array = np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vectors, y_array, test_size=0.2, random_state=42, stratify=y_array
)

In [ ]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, classification_report

nb = BernoulliNB()
nb.fit(X_train, y_train)    # Train

y_pred = nb.predict(X_test) # Predict

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.91
              precision    recall  f1-score   support

           0       1.00      0.81      0.89        47
           1       0.85      1.00      0.92        53

    accuracy                           0.91       100
   macro avg       0.93      0.90      0.91       100
weighted avg       0.92      0.91      0.91       100